[global_config]
  suppress_multiple_term_dialog = True
[keybindings]
[profiles]
  [[default]]
[layouts]
  [[qr_detector]]
    [[[window0]]]
      type = Window
      parent = ""
      title = QR Detector
      size = 1800,900
      maximised = True
    [[[root]]]
      type = HPaned
      parent = window0
      ratio = 0.333
    [[[roscore]]]
      type = Terminal
      parent = root
      profile = default
      title = ROS Master
      command = /home/asus/scripts/start_qr_detector.sh --roscore
    [[[right]]]
      type = HPaned
      parent = root
      ratio = 0.5
    [[[camera]]]
      type = Terminal
      parent = right
      profile = default
      title = RealSense D435 D455
      command = /home/asus/scripts/start_qr_detector.sh --camera
    [[[detector]]]
      type = Terminal
      parent = right
      profile = default
      title = QR Detector
      command = /home/asus/scripts/start_qr_detector.sh --detector
[plugins]
