[global_config]
  suppress_multiple_term_dialog = True
[keybindings]
[profiles]
  [[default]]
[layouts]
  [[uav1_six]]
    [[[window0]]]
      type = Window
      parent = ""
      title = UAV1 传感器规划控制
      size = 1920,1080
      maximised = True
    [[[root]]]
      type = VPaned
      parent = window0
      ratio = 0.5
    [[[top]]]
      type = HPaned
      parent = root
      ratio = 0.333
    [[[step1]]]
      type = Terminal
      parent = top
      profile = default
      title = 1 UAV1 MAVROS
      command = __UAV1_SIX_SCRIPT__ --pane mavros
    [[[top_right]]]
      type = HPaned
      parent = top
      ratio = 0.5
    [[[step2]]]
      type = Terminal
      parent = top_right
      profile = default
      title = 2 UAV1 MID360
      command = __UAV1_SIX_SCRIPT__ --pane mid360
    [[[step3]]]
      type = Terminal
      parent = top_right
      profile = default
      title = 3 UAV1 FAST-LIO
      command = __UAV1_SIX_SCRIPT__ --pane fastlio
    [[[bottom]]]
      type = HPaned
      parent = root
      ratio = 0.333
    [[[step4]]]
      type = Terminal
      parent = bottom
      profile = default
      title = 4 UAV1 视觉位姿
      command = __UAV1_SIX_SCRIPT__ --pane pose
    [[[bottom_right]]]
      type = HPaned
      parent = bottom
      ratio = 0.5
    [[[step5]]]
      type = Terminal
      parent = bottom_right
      profile = default
      title = 5 Diff规划器RViz
      command = __UAV1_SIX_SCRIPT__ --pane planner
    [[[step6]]]
      type = Terminal
      parent = bottom_right
      profile = default
      title = 6 AutoTrans控制器日志
      command = __UAV1_SIX_SCRIPT__ --pane controller
[plugins]
