[global_config]
  suppress_multiple_term_dialog = True
[keybindings]
[profiles]
  [[default]]
[layouts]
  [[uav0_six]]
    [[[window0]]]
      type = Window
      parent = ""
      title = UAV0 传感器检测规划控制
      size = 1920,1080
      maximised = True
    [[[root]]]
      type = VPaned
      parent = window0
      ratio = 0.5
    [[[top]]]
      type = HPaned
      parent = root
      ratio = 0.333
    [[[step1]]]
      type = Terminal
      parent = top
      profile = default
      title = 1 UAV0 MAVROS
      command = __UAV0_SIX_SCRIPT__ --pane mavros
    [[[top_right]]]
      type = HPaned
      parent = top
      ratio = 0.5
    [[[step2]]]
      type = Terminal
      parent = top_right
      profile = default
      title = 2 UAV0 MID360
      command = __UAV0_SIX_SCRIPT__ --pane mid360
    [[[step3]]]
      type = Terminal
      parent = top_right
      profile = default
      title = 3 UAV0 FAST-LIO
      command = __UAV0_SIX_SCRIPT__ --pane fastlio
    [[[bottom]]]
      type = HPaned
      parent = root
      ratio = 0.25
    [[[step4]]]
      type = Terminal
      parent = bottom
      profile = default
      title = 4 UAV0 视觉位姿
      command = __UAV0_SIX_SCRIPT__ --pane pose
    [[[bottom_right]]]
      type = HPaned
      parent = bottom
      ratio = 0.5
    [[[step5]]]
      type = Terminal
      parent = bottom_right
      profile = default
      title = 5 UAV0 检测上报
      command = __UAV0_SIX_SCRIPT__ --pane detection
    [[[bottom_far_right]]]
      type = HPaned
      parent = bottom_right
      ratio = 0.5
    [[[step6]]]
      type = Terminal
      parent = bottom_far_right
      profile = default
      title = 6 UAV0 FUEL规划器RViz
      command = __UAV0_SIX_SCRIPT__ --pane planner
    [[[step7]]]
      type = Terminal
      parent = bottom_far_right
      profile = default
      title = 7 UAV0 AutoTrans控制日志
      command = __UAV0_SIX_SCRIPT__ --pane controller
[plugins]
