width: 384
height: 288
shift_x: 0
shift_y: 0
roi_margin_x: 30
roi_margin_y: 20
threshold_k: 2.0
min_area: 20
max_area: 5000
reject_roi_border_touching: true
publish_rate: 20
display: false
uvc_demo_path: "uvc_demo"
uvc_offset_fix: 0
candidate_detected_topic: "/UAV0/thermal/target_candidate_detected"
candidate_status_topic: "/UAV0/thermal/target_candidate_status"
candidate_pixel_topic: "/UAV0/thermal/target_candidate_pixel"

stable_filter_enable: true
stable_max_len: 3
stable_min_hits: 2
stable_max_pixel_jump: 25
