[global_config]
  suppress_multiple_term_dialog = True
[keybindings]
[profiles]
  [[default]]
[layouts]
  [[precision_landing]]
    [[[window0]]]
      type = Window
      parent = ""
      title = Precision Landing
      size = 1800,900
      maximised = True
    [[[root]]]
      type = VPaned
      parent = window0
      ratio = 0.35
    [[[top]]]
      type = HPaned
      parent = root
      ratio = 0.5
    [[[camera]]]
      type = Terminal
      parent = top
      profile = default
      title = Down Camera
      command = __PRECISION_LANDING_SCRIPT__ --camera
    [[[debug_image]]]
      type = Terminal
      parent = top
      profile = default
      title = ArUco Debug Image
      command = __PRECISION_LANDING_SCRIPT__ --image-view
    [[[mission]]]
      type = Terminal
      parent = root
      profile = default
      title = Takeoff and Landing
      command = __PRECISION_LANDING_SCRIPT__ --mission
[plugins]
